version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
#      - echo Build started on `date`
##      - mvn install -DskipTests
#      - cd "$CODEBUILD_SRC_DIR"
#      - terraform init -input=false
#      - terraform apply -input=false -auto-approve
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform validate
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - '**/*'
#  name: laundrybe
