version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip"
      - "unzip -o terraform.zip"
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
#      - mvn install -DskipTests
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform apply -input=false -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: laundrybe
