version: 0.2

phases:
  install:
    commands:
      - echo Install terraform binary......
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - mvn clean install -DskipTests
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform apply -input=false -auto-approve
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
