version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - tf_version=1.0.11
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
#      - echo Build started on `date`
##      - mvn install -DskipTests
#      - cd "$CODEBUILD_SRC_DIR"
#      - terraform init -input=false
#      - terraform apply -input=false -auto-approve
      - terraform --version
      - terraform init -input=false
      - terraform validate
      - terraform plan -lock=false -input=false
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - '**/*'
#  name: laundrybe
