apiVersion: apps/v1
kind: Deployment
metadata:
  name: laundry
spec:
  selector:
    matchLabels:
      app: laundry
  template:
    metadata:
      labels:
        app: laundry
    spec:
      containers:
        - name: laundry
          image: zonesama/laundry-be:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: laundry-service
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: laundry
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laundry-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: laundry.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laundry-service
                port:
                  number: 80
