apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laundry-be
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: laundry-be
        visualize: "true"
    spec:
      containers:
        - name: laundry-be-pod
          image: zonesama/laundry-be:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: laundry-be-service
spec:
  selector:
    app: laundry-be
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
